version: '3'
services:
  api:
    depends_on:
      - mongo
    build: ./
    container_name: node-api
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network

  mongo:
    image: mongo
    hostname: mongodb
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - ./data/db:/data/db
      - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./.docker/mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
    ports:
      - '27017:27017'

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
